---
version: '2'
services:
  openbmp_aio:
    image: openbmp/aio
    container_name: openbmp_aio
    hostname: openbmp_aio
    environment:
      - API_FQDN=12.1.1.10
    volumes:
      - "/var/openbmp/mysql:/data/mysql"
    ports:
      - 3306:3306
      - 2181:2181
      - 5001:5000
      - 9092:9092
      - 8001:8001

  controller:
    image: akshshar/grpc-openbmp
    container_name: controller
    hostname: controller
    volumes:
      - "/vagrant/lib:/"
    privileged: true
    tty: true

  redisrib:
    image: redis-server 
    container_name: redisrib
    hostname: redisrib
    ports:
      - 6379:6379

  rshuttle:
    image: akshshar/grpc-openbmp
    container_name: rshuttle
    hostname: redisrib
    volumes:
      - "/vagrant/route-shuttle:/"
    ports:
      - 6379:6379

